CXX = icc
CXXFLAGS = -std=c++11 -pthread -O3


.PHONY: all_build build clean

all_build: build main.out

main.out: main.cpp build/Matrix.o build/Barrier.o
	$(CXX) $^ $(CXXFLAGS) -DNO_OPENCV -o $@

build/%.o: %.cpp %.hpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

build:
	mkdir -p build

clean:
	rm -Rvf build main.out
