all_build: build main.mic.out

main.mic.out: main.cpp build/Matrix.o
	icpc main.cpp build/Matrix.o \
			-std=c++11 \
			-DNO_OPENCV \
			-pthread \
			-O3 \
			-o main.mic.out

build/Matrix.o: Matrix.cpp
	icpc Matrix.cpp \
			-c \
			-std=c++11 \
			-O3 \
			-o build/Matrix.o

build:
	mkdir -p build
