CXX = icc
CXXFLAGS = -std=c++11 -pthread -O3 #-qopt-report=5 -qopt-report-phase=vec


.PHONY: all build clean

all: build main.out

main.out: main.cpp build/Matrix.o build/Barrier.o
	$(CXX) $^ $(CXXFLAGS) -DEXTREME_TEST -DSETAFFINITY -o $@

build/%.o: %.cpp %.hpp
	$(CXX) $(CXXFLAGS) -c -o $@ $<

build:
	mkdir -p build

clean:
	rm -Rvf build main.out
